### ISSUE TITLE
admin.register decorator

### ISSUE THREAD

**Issue by namper** [Cakelover-png/car_wash#1]
https://github.com/Cakelover-png/car_wash/blob/5ce43be16f56b1d3dc5d196de4946aed98375cfd/management/admin.py#L13

აქ ჯობია @admin.register დეკორატორი გამოიყენო

**Comment by Cakelover-png** [comment]
ვფიქრობდი გამოყენებაზე, მაგრამ მეთქი რა აზრი აქვსთქვა.
მაგრამ შევცვალე.
